### ISSUE TITLE
Building docker image not working

### ISSUE THREAD

**Issue by kleyton67** [kfeine/Attendize#14]
I am trying to build this project, but is not working, follow the steps i have done.

- Create .env file:

```
ATTENDIZE_DEV=true
ATTENDIZE_CLOUD=false

APP_NAME=Attendize
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=https://10.28.33.120:8180

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3306
DB_DATABASE=attendize
DB_USERNAME=attendize
DB_PASSWORD=pass

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=maildev
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

# Attendize Variables
DEFAULT_DATEPICKER_SEPERATOR="-"
DEFAULT_DATEPICKER_FORMAT="yyyy-MM-dd HH:mm"
DEFAULT_DATETIME_FORMAT="Y-m-d H:i"
APP_TIMEZONE=

MAIL_FROM_ADDRESS=testing@attendize.com
MAIL_FROM_NAME=testing_service

# https://github.com/NitMedia/wkhtml2pdf#driver-types
WKHTML2PDF_BIN_FILE=wkhtmltopdf-amd64

# Google Analytics
GOOGLE_ANALYTICS_ID=
GOOGLE_MAPS_GEOCODING_KEY=

# Captcha Configuration
CAPTCHA_IS_ON=false
# can be recaptcha or hcaptcha
CAPTCHA_TYPE=
CAPTCHA_KEY=
CAPTCHA_SECRET=

TWITTER_WIDGET_ID=

LOG=errorlog
```

- Changed dockrfile for my ports / volume:

```
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    env_file:
      - ./.env
    ports:
    - "8180:80"
    networks:
      - attendizenet
    volumes:
      - .:/usr/share/nginx/html/attendize
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    depends_on:
      - db
      - maildev
      - redis
    volumes:
      - .:/usr/share/nginx/html/attendize
    networks: 
      - attendizenet
  composer:
    build:
      context: .
      dockerfile: Dockerfile-composer
    depends_on:
      - php
    volumes:
      - .:/usr/share/nginx/html/attendize
    networks:
      - attendizenet
  php-worker:
    build:
      context: .
      dockerfile: Dockerfile-php
    depends_on:
      - db
      - maildev
      - redis
    volumes:
      - .:/usr/share/nginx/html/attendize
    command: php artisan queue:work --daemon
    networks:
      - attendizenet
  db:
    image: mysql:5.7.22
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "yes"
      MYSQL_HOST: ${DB_HOST}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"
    networks:
    - attendizenet
  maildev:
    image: djfarrelly/maildev
    ports:
      - "8182:80"
    networks:
      - attendizenet
  redis:
    image: redis
    networks:
      - attendizenet

networks:
  attendizenet:
    driver: bridge

volumes:
  mysql-data:

```

- run docker compose build;

- run docker compose up -d ;

Expected behavior: All containers up and after while the response on 0.0.0.0:8180;
Current Behavior: 

php-worker stops with the message:
```
php-worker-1  | Fatal error: require(): Failed opening required '/usr/share/nginx/html/attendize/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /usr/share/nginx/html/attendize/bootstrap/autoload.php on line 17
```

If i try up with docker compose up -d  web

The web page show:
```
Warning: require(/usr/share/nginx/html/attendize/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /usr/share/nginx/html/attendize/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/usr/share/nginx/html/attendize/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /usr/share/nginx/html/attendize/bootstrap/autoload.php on line 17
```
